hood_watch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^hoods/', include('hoods.urls', namespace='hoods')),
]

hoods/urls.py
from django.conf.urls import url
from . import views

app_name = 'hoods'
urlpatterns = [
    url(r'^$', views.ListHoods.as_view(), name='all'),
    url(r'^new/$', views.CreateHood.as_view(), name='create'),
    url(r'businesses/in/(?P<slug>[-\w]+)/$', views.SingleHood.as_view(), name='single'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinHood.as_view(), name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$', views.LeaveHood.as_view(), name='leave'),

]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.BusinessList.as_view(), name='all'),
    url(r'new/$', views.CreateBusiness.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)', views.UserBusinesses.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.BusinessDetail, name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeleteBusiness.as_view(), name='delete'),
]

hoods/models.py
from django.db import models
from django.utils.text import slugify
from django import template
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse


# Create your models here.
User = get_user_model()
register = template.Library

class Hood(models.Model):
    name = models.CharField(max_length=140, unique=True)
    slug = models.SlugField(allow_unicode=True,  unique=True)
    location = models.CharField(max_length=140, blank=True, default='')
    occupants = models.ManyToManyField(User, through='HoodMember')


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('hoods:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']

class HoodMember(models.Model):
    hood = models.ForeignKey(Hood, related_name='memberships')
    user = models.ForeignKey(User, related_name='user_hoods')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('hood', 'user')

hoods/views.py
from django.contrib import messages
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views import generic
from hoods.models import Hood, HoodMember

# Create your views here.


class CreateHood(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'location')
    model = Hood


class SingleHood(generic.DetailView):
    model = Hood


class ListHoods(generic.ListView):
    model = Hood

class JoinHood(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('hoods:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        hood = get_object_or_404(Hood, slug=self.kwargs.get('slug'))

        try:
            HoodMember.objects.create(user=self.request.user, hood=hood)
        except IntegrityError:
            messages.warning(self.request, 'You are already a member!')
        else:
            messages.success(self.request, 'Congratulatoins!! You are now a member!')

        return super().get(request, *args, **kwargs)


class LeaveHood(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('hoods:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = HoodMember.objects.filter(user=self.request.user, hood__slug=self.kwargs.get('slug')).get()
        except HoodMember.DoesNotExist:
            messages.warning(self.request, 'Sorry your are not a member here!')
        else:
            membership.delete()
            messages.success(self.request, 'You are no longer a member!')

        return super().get(request, *args, **kwargs)

hoods/templates/hoods/hood_base.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row">
    {% block prehood %} {% endblock %}
    {% block hood_content %} {% endblock %}
    {% block posthood %} {% endblock %}
  </div>
</div>

{% endblock %}

hoods/templates/hoods/hood_detail.html
{% extends "hoods/hood_base.html" %}
{% block prehood %}

  <div class="col-sm-6">
    <div class="card" style="width: 18rem; margin-top: 20%">
      <div class="card-body">
        <h5 class="card-title">{{hood.name|title }} Hood</h5>
        <p class="card-text">Members: {{hood.occupants.count}}</p>
        {% if user in hood.occupants.all %}
        <a href="{% url 'hoods:leave' slug=hood.slug %}" class="btn btn-danger">Leave</a>
        {% else %}
        <a href="{% url 'hoods:join' slug=hood.slug %}" class="btn btn-primary">Join</a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="col-sm-6">
  </div>

{% endblock %}
{% block hood_content %}
<div class="mt-3 ml-3">
  <div class="card">
  {% if hood.businesses.count == 0 %}
  <h4>No Businesses in this hood yet!</h4>
  {% if user in hood.occupants.all %}
  <a href="{% url 'posts:create' %}"><button class="btn btn-primary" style="">Create Business</button> </a>
  {% endif %}
  {% else %}
    {% for business in hood.businesses.all %}
     {% include "posts/_post.html" %}
    {% endfor %}
  {% endif%}
</div>
</div>

{% endblock %}

hoods/templates/hoods/hood_form.html
{% extends "hoods/hood_base.html" %} {% load bootstrap4 %} 
{% block hood_content %}
<div class="container ">
  <div class="row" >
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
      <div class="card" style=" margin-top: 22%">
        <h5 class="card-header text-center">Create New Hood</h5>
        <div class="card-body">
          <form action="{% url 'hoods:create'%}" method="post">
            {% csrf_token %} {% bootstrap_form form %}
            <input type="submit" class="btn btn-success" value="Create">
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>
  {% endblock %}

hoods/templates/hoods/hood_list.html
{% extends "hoods/hood_base.html" %} {% block prehood %}
<div class="row mt-2" ">
  <div class="col-md-4">
    {% if user.is_authenticated %}
    <p>Welcome 
      <a href="{% url 'posts:for_user' username=user.username%}">@{{user.username}}</a> {% endif %}<br/> Welcome to the hoods page!</p>
    {% if user.is_authenticated%}
    <a  class="btn btn-sm btn-primary" href="{% url 'hoods:create' %}">Create Hood</a> 
    {% endif %}
  </div>
  {% endblock %} {% block hood_content %}
    <div class="row">
      {% for hood in object_list %}
      <div class="col-md-4">
        <div class="card mt-2 text-white bg-dark mb-3" >
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'hoods:single' slug=hood.slug %}">{{hood.name}}</a></h5>
            <h6 class="card-subtitle mb-2 text-muted">{{hood.location}}</h6>
            <p class="card-text"><span class="badge badge-secondary">{{hood.occupants.count}}</span> occupant{{hood.occupants.count|pluralize}}</p>
            <p class="card-text"><span class="badge badge-secondary">{{hood.businesses.count}}</span> business{{hood.businesses.count|pluralize}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>


{% endblock %}