accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup')
]

hood_watch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^hoods/', include('hoods.urls', namespace='hoods')),
]

hoods/urls.py
from django.conf.urls import url
from . import views

app_name = 'hoods'
urlpatterns = [
    url(r'^$', views.ListHoods.as_view(), name='all'),
    url(r'^new/$', views.CreateHood.as_view(), name='create'),
    url(r'businesses/in/(?P<slug>[-\w]+)/$', views.SingleHood.as_view(), name='single'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinHood.as_view(), name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$', views.LeaveHood.as_view(), name='leave'),

]

templates/base.html
{% load bootstrap4 %}
{% load static%}
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://i.imgur.com/PbCNmPB.png" type="image/x-icon">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Linda Hood</title>
</head>

<body style="background: url(https://images.unsplash.com/photo-1499310392581-322cec0355a6?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjF9&s=195675111b0e52404509f50a6adde11d); background-position: center;background-repeat: no-repeat;background-attachment: fixed;   background-size: cover;
  ">
<!--   <nav class="navbar  navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="#" width="30" height="30" class="d-inline-block align-top" alt="">
      Linda Hood
    </a>
    {% if user.is_authenticated %}<a href="https://imgur.com/PbCNmPB"><img src="https://i.imgur.com/PbCNmPB.png" title="source: imgur.com" /></a>
      <a href="{% url 'accounts:logout' %}">
        <button style="margin-right: 50px" class="btn btn-danger" id="navbarNavDropdown">Logout</button> 
      </a>
    {% endif %}
    </div> 
  </nav>
 -->  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation" style="height: 60px; border-bottom: solid orange 2px;">
    <div class="navbar-header" style=" float: left;padding: 15px; text-align: center;width: 100%;">
      <a class="navbar-brand" href="{% url 'home' %}" style="float:none;">
        <img src="https://i.imgur.com/PbCNmPB.png" width="30" height="30" class="d-inline-block align-top" alt="">
        Linda Hood
      </a>
    </div>
    {% if user.is_authenticated %}
      <a href="{% url 'accounts:logout' %}">
        <button style="margin-right: 50px" class="btn btn-danger btn-sm" id="navbarNavDropdown">Logout</button> 
      </a>
    {% endif %}
  </nav>
  {% block content %} 
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load bootstrap4%}
{% load static%}

{% block content %}
<div class="container" style="margin: 10%"> 
	<div class="row">
		<div class="col-md-6 offset-md-3" >
			<div class="jumbotron">
				<h1 > Karibu sana {{user.username|title}} to <strong>Linda Hood</strong>  </h1>

			{% if user.is_authenticated %}
		    
		      <a href="{% url 'hoods:create' %}"><button class="btn btn-primary btn-lg">Create Hood</button></a>
		      <a href="{% url 'posts:create' %}"><button class="btn btn-success btn-lg">Create Business</button> </a>
		      <a href="{% url 'hoods:all' %}"><button class="btn btn-secondary btn-lg">All Hoods</button></a>
		    </div>
	  	</div>
	</div>
</div>
{% endif %} 
{% endblock %}

templates/navbar.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="#" width="30" height="30" class="d-inline-block align-top" alt="">
      Linda Hood
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  	</button>
</nav>
  {% endblock %}