hood_watch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^hoods/', include('hoods.urls', namespace='hoods')),
]

hoods/urls.py
from django.conf.urls import url
from . import views

app_name = 'hoods'
urlpatterns = [
    url(r'^$', views.ListHoods.as_view(), name='all'),
    url(r'^new/$', views.CreateHood.as_view(), name='create'),
    url(r'businesses/in/(?P<slug>[-\w]+)/$', views.SingleHood.as_view(), name='single'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinHood.as_view(), name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$', views.LeaveHood.as_view(), name='leave'),

]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.BusinessList.as_view(), name='all'),
    url(r'new/$', views.CreateBusiness.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)', views.UserBusinesses.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.BusinessDetail, name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeleteBusiness.as_view(), name='delete'),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from hoods.models import Hood
from django.contrib.auth import get_user_model


# Create your models here.
User = get_user_model()


class Business(models.Model):
    user = models.ForeignKey(User, related_name="businesses")
    created_at = models.DateTimeField(auto_now=True)
    business_name = models.CharField(max_length=140, blank=True, null=True)
    business_email = models.EmailField(max_length=70, blank=True)
    hood = models.ForeignKey(Hood, related_name='businesses', null=True, blank=True)

    def __str__(self):
        return self.business_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username, 'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'business_name']

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy

from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib.auth import get_user_model

# Create your views here.
User = get_user_model()


class BusinessList(SelectRelatedMixin, generic.ListView):
    model = models.Business
    select_related = ('user', 'hood')

class UserBusinesses(generic.ListView):
    model = models.Business
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.business_user = User.objects.prefetch_related('businesses').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.business_user.businesses.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['business_user'] = self.business_user
        return context


class CreateBusiness(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('business_name', 'business_email', 'hood')
    model = models.Business

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class BusinessDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Business
    select_related = ('user', 'hood')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user___username__iexact=self.kwargs.get('username'))


class DeleteBusiness(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Business
    select_related = ('user', 'hood')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Business Deleted')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="post" style="margin-top: 10%">
  <div class="card" >
      <h5 class="card-header card-header text-center" >Business name : {{business.business_name}}</h5>

    <div class="card-body">
      <p>Business Email : {{business.business_email}}</p>
      <p><strong>Proprietor : {{business.user.username}}</strong></p>
      <a href="{% url 'posts:for_user' username=business.user.username %}"></a>
      <time><a href="{% url 'posts:single' username=business.user.username pk=business.pk %}"></a></time>
    </div>

    <div class="content">
      {% if user.is_authenticated and business.user == user %}
      <a href="{% url 'posts:delete' pk=business.pk %}" title="delete" class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
</div>

posts/templates/posts/business_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<div class="card" style="margin-top: 6%">
<div class="posts">
<h4>Are you sure you want to Delete this business?</h4>
  {% include "posts/_post.html" with business=object hide_delete=True %}
  <form method="post">
    {% csrf_token %}
<!--     <input type="submit" value="Confirm Delete" class="btn btn-warning">
 -->    <a class="btn btn-primary" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
  </form>
</div>

</div>

{% endblock %}

posts/templates/posts/business_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}
{% block post_content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
      <div class="card" style="width: 18rem;margin-top: 20%">
        <h5 class="card-header text-center">Create New Business</h5>
        <div class="card-body">
          <form action="{% url 'posts:create'%}" method="post">
            {% csrf_token %} {% bootstrap_form form %}
            <input type="submit" class="btn btn-success" value="Post">
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>
{% endblock %}

posts/templates/posts/business_list.html
{% extends "posts/post_base.html" %}
{% block pre_post_content %}
<div class="col-md-4 mt-3">
  <h5>@{{user.username}}</h5>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-6 mt-3">
  {% if business_list.count == 0 %}
  <h4>No Businesses for this user yet!</h4>
  {% else %}
    {% for business in business_list %}
     {% include "posts/_post.html" %}
    {% endfor %}
  {% endif%}
</div>
{% endblock %}

posts/templates/posts/post_base.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row">
    {% block pre_post_content %} {% endblock %}
    {% block post_content %} {% endblock %}
    {% block post_post %} {% endblock %}

  </div>
</div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% load bootstrap4%}
{% load static%}

{% block post_content%}
<div class="col-md-4">
  {% include "posts/_post.html" %}
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %} {% block pre_post_content %} {% if request.user.is_authenticated %}
<div class="col-md-6">
  <div class="card">
    <div class="content">
      <h5>Your Hoods</h5> {% for member_hood in ger_user_hoods %}
      <a href="{% url 'hoods:single' slug=member_hood.hood.slug %}"></a> {% endfor %}
    </div>
  </div>
  {% endif %}
  <div class="card">
    <div class="content">
      <h5>All Hoods</h5> {% for other_hood in get_other_hoods %}
      <a href="{% url 'hoods:single' slug=other_hood.slug %}"></a> {% endfor %}
    </div>
  </div>
</div>

{% endblock %} {% block post_content %}
<div class="col-md-6">
  {% for business in business_list %} {% include "posts/_post.html" %} {% endfor %}

</div>

{% endblock %}